### PR TITLE
Support JWT with ES256K (secp256k1) signature #263

### PR DESCRIPTION
**Pull request by haleystorm**
This is an updated version of @marksalpeter's PR https://github.com/go-jose/go-jose/pull/14 that adds support for the secp256k1 curve to the latest v3 head. The decred dependency was also bumped to v4 of the curve. It works for signing, encryption and key wrapping. https://github.com/square/go-jose/issues/263

*Note: This PR updates @marksalpeter's PR to the latest v3 head. I have not made any additional changes.*

cc @csstaub

### CODE REVIEW

**Comment by haleystorm** [comment]
Hi @aarongable please take a look when you have a chance. Thank you!

**Comment by mcpherrinm** [comment]
I don’t think we should be taking a large third party dependency here.  What’s the motivation for supporting these curves?  There’s little adoption of secp256k1 outside of cryptocurrency use cases, which aren’t typically interested in JOSE

**Comment by jsha** [comment]
I also think we shouldn't support secp256k1 without a strong use case. Thanks for the contribution. Closing for now.

**Comment by haleystorm** [comment]
> I don’t think we should be taking a large third party dependency here. What’s the motivation for supporting these curves? There’s little adoption of secp256k1 outside of cryptocurrency use cases, which aren’t typically interested in JOSE

Fair. An acceptable alternative is to merge https://github.com/go-jose/go-jose/issues/25

I am using coreos/go-oidc to implement an OIDC client which depends on go-jose. When testing my OIDC client against the [OIDC conformance suite](https://www.certification.openid.net/) (written in java) it fails because the test server jwks contains a secp256k key.

**Pull request closed without merging**
