### PR TITLE
jws: Add expected algorithms for signatures

### PR DESCRIPTION
**Pull request by jsha**
Following the example of #69

### CODE REVIEW

**Review by aarongable — APPROVED** [review]

**Comment by valters** [comment]
Could you provide a migration guide when upgrading from v3, I have a call  like 
```
	parsedJwt, err := jwt.ParseSigned(encodedJwt)
	if err != nil {
		return "", err
	}
```
Now I need to know what algorithm the encodedJwt is using, but I don't necessarily know what it is or what to expect.
I need to provide a list `SignatureAlgorithm`, a `[]SignatureAlgorithm`, but is there a simple way to get common ones?

**Comment by mcpherrinm** [comment]
The full list of algorithims supported is:

https://github.com/go-jose/go-jose/blob/696da50b9ef6b1fc40668b3126ae1d4163c1d194/shared.go#L106-L118

What algorithms you want to support depends on your use-case. This parameter was added because it is often unsafe to blindly accept any algorithm.

**Comment by valters** [comment]
Would it be possible to add a helper function `all()` or `any()` that just returns all of them so I don't have to make this list on my side?

**Comment by mcpherrinm** [comment]
We'd rather not, as that's generally not a safe behaviour, and would potentially be a silent breaking change if we ever removed algorithms.

**Comment by jsha** [comment]
What is the system that produces the JWTs you're parsing? If it's a system you control, you can look at the source code and see what algorithm it uses to sign its output. If it's not a system you control, it should document the algorithms it uses, and you can use that documentation. And if there's no documentation of that, there's a good reason to file an enhancement request. 😄

**Pull request merged**
