### PR TITLE
Support JWT with ES256K (secp256k1) signature #263

### PR DESCRIPTION
**Pull request by marksalpeter**
This is an updated version of @kdimak's PR square/go-jose#278 that adds support for the `secp256k1` curve to the latest `v3` head. The `decred` dependency was also bumped to `v4` of the curve. It works for signing, encryption and key wrapping. square/go-jose#263

---

Here's an example of a fairly complicated use of JWE that I'm preparing to incorporate into [securely.so](https://securely.so) for those who are interested in doing something similar.

```go

func ExampleNewMultiEncrypter() {
	// Generate a public/private RSA pair for the first recipient
	rsaPrivateKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		panic(err)
	}

	// Generate a public/private ES256K key pair to use for the second recipient
	ecPrivateKey, err := ecdsa.GenerateKey(secp256k1.S256(), rand.Reader)
	if err != nil {
		panic(err)
	}

	// Generate a shared AES-GCM-256 key
	aesSharedKey := make([]byte, 32)
	if _, err := rand.Read(aesSharedKey); err != nil {
		panic(err)
	}

	// Instantiate an encrypter using RSA-OAEP with AES128-GCM. An error would
	// indicate that the selected algorithm(s) are not currently supported.
	encrypter, err := jose.NewMultiEncrypter(jose.A256GCM, []jose.Recipient{
		{Algorithm: jose.RSA_OAEP, Key: &rsaPrivateKey.PublicKey, KeyID: "1"},
		{Algorithm: jose.ECDH_ES_A256KW, Key: &ecPrivateKey.PublicKey, KeyID: "2"},
		{Algorithm: jose.A256GCMKW, Key: aesSharedKey},
	}, nil)
	if err != nil {
		panic(err)
	}

	// Encrypt a sample plaintext. Calling the encrypter returns an encrypted
	// JWE object, which can then be serialized for output afterwards. An error
	// would indicate a problem in an underlying cryptographic primitive.
	var plaintext = []byte("Lorem ipsum dolor sit amet")
	object, err := encrypter.Encrypt(plaintext)
	if err != nil {
		panic(err)
	}

	// Serialize the encrypted object using the full serialization format.
	// Alternatively you can also use the compact format here by calling
	// object.CompactSerialize() instead.
	serialized := object.FullSerialize()
	var b bytes.Buffer
	if err := json.Indent(&b, []byte(serialized), "", "  "); err != nil {
		panic(err)
	}
	fmt.Println("jwe:", b.String())

	// Parse the serialized, encrypted JWE object. An error would indicate that
	// the given input did not represent a valid message.
	object, err = jose.ParseEncrypted(serialized)
	if err != nil {
		panic(err)
	}

	// Now we can decrypt and get back our original plaintext. An error here
	// would indicate that the message failed to decrypt, e.g. because the auth
	// tag was broken or the message was tampered with.
	decrypt := func(privateKey interface{}) {
		i, header, decrypted, err := object.DecryptMulti(privateKey)
		if err != nil {
			panic(err)
		}
		fmt.Printf("recipient %d, %-15s, %s\n", i, header.Algorithm, string(decrypted))
	}
	decrypt(rsaPrivateKey)
	decrypt(ecPrivateKey)
	decrypt(aesSharedKey)
	// Output
	// jwe: {
	// 	"protected": "eyJlbmMiOiJBMjU2R0NNIn0",
	// 	"recipients": [
	// 	  {
	// 		"header": {
	// 		  "alg": "RSA-OAEP",
	// 		  "kid": "1"
	// 		},
	// 		"encrypted_key": "KWSEhYc3yJTWtkL6s2ziI3_m3Rear2H-HdyIcfNvK44NQR2DkUzQluLiAWi_uvWdtXikzQCGAyP1ge7O10BrJ_NAk0NoTHdCHukO2ZpJ5z5LrvMHmtzWkDvlXFHYDulOGaUiWb3q5opVVOYDMGZbE5RrphJwXex34bQSAzjPopLdkTEPHAilhfQlpLk_3BXzB2zNRSACfWbY_mR2_Gg8Tm216ktLvAkhdDOmR6BxaEgPom3bUThXNJFT_1S5cOyagPd3g3r4qduYwNgoLlGAi_z4qDljXwJttni2M8mUdBZVGfSW0FRqON_ee1d2WygvQ_7S5BUXQkN77BViiUBigA"
	// 	  },
	// 	  {
	// 		"header": {
	// 		  "alg": "ECDH-ES+A256KW",
	// 		  "epk": {
	// 			"kty": "EC",
	// 			"crv": "secp256k1",
	// 			"x": "mNNrv9KiEfOFJ-3gRBRt-hkRaYyyP6utUD1aH4ymr0k",
	// 			"y": "vwlt-qbOdpZzMkBhH6ZpdpISj_H5lit0R-dxe5kW0Y8"
	// 		  },
	// 		  "kid": "2"
	// 		},
	// 		"encrypted_key": "0ffZwfbk5tjnEUnF50G6UDpBjQGRUXBUwmD__qEbGJIB1en-nc2uzg"
	// 	  },
	// 	  {
	// 		"header": {
	// 		  "alg": "A256GCMKW",
	// 		  "iv": "o6ddvVN1OuN6lS3S",
	// 		  "tag": "Fg8GgvnUDOjhPAcc5DjQEQ"
	// 		},
	// 		"encrypted_key": "osT5LSwZRITCVv3KlxSauahl7bq1lgr0hSpICGmmzWc"
	// 	  }
	// 	],
	// 	"encrypted_key": "KWSEhYc3yJTWtkL6s2ziI3_m3Rear2H-HdyIcfNvK44NQR2DkUzQluLiAWi_uvWdtXikzQCGAyP1ge7O10BrJ_NAk0NoTHdCHukO2ZpJ5z5LrvMHmtzWkDvlXFHYDulOGaUiWb3q5opVVOYDMGZbE5RrphJwXex34bQSAzjPopLdkTEPHAilhfQlpLk_3BXzB2zNRSACfWbY_mR2_Gg8Tm216ktLvAkhdDOmR6BxaEgPom3bUThXNJFT_1S5cOyagPd3g3r4qduYwNgoLlGAi_z4qDljXwJttni2M8mUdBZVGfSW0FRqON_ee1d2WygvQ_7S5BUXQkN77BViiUBigA",
	// 	"iv": "jpPVWLfZ_1b-1iML",
	// 	"ciphertext": "LvWQwCTR2wy7eH1M6y8xSgOwTqKLbg_oCDE",
	// 	"tag": "f4fXtzGaLA9DjXuM38kemQ"
	// }
	// recipient 0, RSA-OAEP       , Lorem ipsum dolor sit amet
	// recipient 1, ECDH-ES+A256KW , Lorem ipsum dolor sit amet
	// recipient 2, A256GCMKW      , Lorem ipsum dolor sit amet
}
```

### CODE REVIEW

**Comment by shaneing** [comment]
How is the process going?

**Comment by jsha** [comment]
As mentioned in https://github.com/go-jose/go-jose/pull/59#issuecomment-1813448843, we're unlikely to support secp256k1 at this time. Thanks for the contribution.

**Comment by ryanobjc** [comment]
This is a vote for interest/need of secp256k1.

Given the pushback in other comments, there is little/no appetite for adding support for other curves?

**Comment by mcpherrinm** [comment]
If upstream Golang crypto supports the curve, I think we’re willing to take it on, but we don’t want to use a third party library for secp256k1.

**Pull request closed without merging**
