### PR TITLE
Update jose-util to use /v4, drop kingpin

### LINKED ISSUE #11: go.mod in jose-util is out of date
https://github.com/go-jose/go-jose/blob/32586461b3c47b961798d2c57e46e6431baa91f1/jose-util/go.mod#L8

go.mod should 
1. correct hash
2. have correct version for go.1.16 at least.

suggest to update dependency there.

# how to replicate

`go get -u github.com/go-jose/go-jose/jose-util`

or create a main.go, import jose-util

# log

```sh
 go get -u github.com/go-jose/go-jose/jose-util
go get: github.com/go-jose/go-jose/jose-util@v0.0.0-20220520230150-32586461b3c4 requires
        github.com/go-jose/go-jose/v3@v3.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

### PR DESCRIPTION
**Pull request by mcpherrinm**
- Remove jose-util's go.mod
- Specify algorithms in jose-util for ParseSigned and ParseEncrypted
- Drop kingpin for the standard flag package

Fixes #11, #52

### CODE REVIEW

**Review by jsha — CHANGES_REQUESTED** [review]
I see that removing jose-util's go.mod means taking kingpin (a flag parser) as a dependency of the core go-jose module. That's a real bummer - I'd really like to keep the core module's dependencies as slim as possible. I think that reason alone is enough to keep jose-util as its own module, since there are many users of the library that don't use jose-util.

**Comment by jsha** [comment]
Although, hm, dependencies are on a package level rather than a module level, so other packages that depend on the main package will not actually pull in kingpin, because the main package does not import it. 🤔

**Comment by mcpherrinm** [comment]
Kingpin isn't really actively updated, and we're not using many features from it.  Let me see if I can just drop it

**Comment by mcpherrinm** [comment]
jose-util had a cram test that wasn't being used, so I pulled it back in.

most of the work in dropping kingpin was that `app.FatalIfError` was used all over; I swapped it for returning errors.

**Pull request merged**
