### PR TITLE
Fix allow multiple audiences

### PR DESCRIPTION
**Pull request by shnmorimoto**
Original issue is https://github.com/square/go-jose/issues/286
And PR for v2 is https://github.com/square/go-jose/pull/369

This PR allows multiple audiences.

Test result is below
```
$ go test ./jwt
ok      github.com/go-jose/go-jose/v3/jwt

```

### CODE REVIEW

**Comment by shnmorimoto** [comment]
@csstaub Sorry for bothering you.
Could you review this PR when you have a moment?

**Review by csstaub — APPROVED** [review]
LGTM. Thank you for the pull request!

**Comment by shnmorimoto** [comment]
@csstaub Thank you so much!

**Comment by sergiughf** [comment]
Hey @shnmorimoto appreciate the fix provided over here. 

@csstaub I'm wondering if we could merge go-jose/go-jose@v2 branch with the latest from square/go-jose and then incorporate this fix in there as well so we could make use of it already?

Or alternatively is the v3 still under development and not stable yet? Or is the README simply outdated?:) 

Appreciate your time in answering these! 🙇🏻

**Comment by jsha** [comment]
Confirming that the new behavior is correct per [RFC 7519 Section 4.1.3](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.3):

> 4.1.3.  "aud" (Audience) Claim
>
>   The "aud" (audience) claim identifies the recipients that the JWT is
>   intended for.  Each principal intended to process the JWT MUST
>   identify itself with a value in the audience claim.  If the principal
>   processing the claim does not identify itself with **a value** in the
>   "aud" claim when this claim is present, then the JWT MUST be
>   rejected.  In the general case, the "aud" value is an array of case-
>   sensitive strings, each containing a StringOrURI value.  In the
>   special case when the JWT has one audience, the "aud" value MAY be a
>   single case-sensitive string containing a StringOrURI value.  The
>   interpretation of audience values is generally application specific.
>   Use of this claim is OPTIONAL.

(emphasis mine)

**Pull request merged**
